export const READINESS_PAGES = [
  { route: "/", check: "landing", apis: [] },
  { route: "/login", check: "login", apis: [] },
  { route: "/privacy", check: "privacy", apis: [] },
  { route: "/dashboard", check: "overview", apis: ["/api/usage#5", "/api/pricing", "/api/usage/by-device", "/api/seasons?status=ended"] },
  { route: "/devices", check: "devices", apis: ["/api/usage/by-device", "/api/usage?deviceId", "/api/pricing"] },
  { route: "/agents", check: "agents", apis: ["/api/usage", "/api/pricing", "/api/pricing/models"] },
  { route: "/models", check: "models", apis: ["/api/usage", "/api/pricing", "/api/pricing/models"] },
  { route: "/daily-usage", check: "daily", apis: ["/api/usage", "/api/usage/by-device", "/api/pricing"] },
  { route: "/hourly-usage", check: "hourly", apis: ["/api/usage#2", "/api/usage/by-device#2", "/api/pricing"] },
  { route: "/sessions", check: "sessions", apis: ["/api/sessions", "/api/usage#2", "/api/usage/by-device"] },
  { route: "/manage-devices", check: "manageDevices", apis: ["/api/devices"] },
  { route: "/model-prices", check: "prices", apis: ["/api/pricing/models"] },
  { route: "/settings/general", check: "settings", apis: ["/api/settings"] },
  { route: "/settings/organizations", check: "organizations", apis: ["/api/organizations", "/api/organizations/mine"] },
  { route: "/teams", check: "teams", apis: ["/api/teams"] },
  { route: "/teams/[teamId]", check: "team", apis: ["/api/teams/[teamId]", "/api/seasons"] },
  { route: "/leaderboard", check: "leaderboard", apis: ["/api/leaderboard"] },
  { route: "/leaderboard/harness", check: "leaderboard", apis: ["/api/leaderboard?source=claude-code"] },
  { route: "/leaderboard/models", check: "leaderboard", apis: ["/api/leaderboard?model=claude-opus-4.6-1m"] },
  { route: "/leaderboard/seasons", check: "seasons", apis: ["/api/seasons"] },
  { route: "/leaderboard/seasons/[slug]", check: "season", apis: ["/api/seasons/[slug]/leaderboard"] },
  { route: "/u/[slug]", check: "profile", apis: ["/api/users/[slug]#3", "/api/pricing"] },
  { route: "/admin/invites", check: "invites", apis: ["/api/admin/invites", "/api/admin/settings"] },
  { route: "/admin/organizations", check: "adminOrganizations", apis: ["/api/admin/organizations"] },
  { route: "/admin/seasons", check: "adminSeasons", apis: ["/api/admin/seasons"] },
  { route: "/admin/storage", check: "storage", apis: ["/api/admin/storage", "/api/admin/cache"] },
  { route: "/admin/compare", check: "compare", apis: ["/api/admin/storage"] },
  { route: "/admin/compare/result", check: "comparison", apis: ["/api/admin/usage/compare"] },
] as const;

export const READINESS_REDIRECTS = [
  { from: "/settings", to: "/settings/general", page: true, status: 307 },
  { from: "/admin/compare/result", to: "/admin/compare", page: false, status: 200 },
  { from: "/leaderboard/agents", to: "/leaderboard/harness", page: false, status: 308 },
  { from: "/projects", to: "/dashboard", page: false, status: 308 },
  { from: "/manage-projects", to: "/dashboard", page: false, status: 308 },
  { from: "/leaderboard/achievements", to: "/leaderboard", page: false, status: 308 },
  { from: "/leaderboard/showcases", to: "/leaderboard", page: false, status: 308 },
  { from: "/settings/showcases", to: "/dashboard", page: false, status: 308 },
  { from: "/admin/showcases", to: "/dashboard", page: false, status: 308 },
  { from: "/admin/model-prices", to: "/model-prices", page: false, status: 308 },
] as const;
